/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function assignProcess(token: number, pid: number): void

export declare function closeJob(token: number): void

/**
 * Create the session's containment scope. Main must retain the returned token
 * for the whole session lifetime.
 */
export declare function createKillOnCloseJob(sessionId?: string | undefined | null): number

export interface DirectoryIdentity {
  selectedPath: string
  canonicalPath: string
  displayPath: string
  volumeSerial: string
  fileId: string
  driveType: string
  isReparsePoint: boolean
}

export declare function inspectJob(token: number): JobSnapshot

export declare function inspectSessionScope(sessionId: string): JobSnapshot

export interface JobSnapshot {
  activeProcessCount: number
  processIds: Array<number>
  truncated: boolean
}

/** Resolve stable identity for a directory the user picked natively. */
export declare function resolveDirectory(selectedPath: string): DirectoryIdentity

export declare function terminateJob(token: number, exitCode: number): JobSnapshot

export declare function verifyProcessInJob(token: number, pid: number): boolean
